# Generated by Django 4.1.7 on 2023-04-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathsu_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='picture',
            field=models.ImageField(default='newImage.jpg', upload_to='Member_pics'),
        ),
    ]
