# Generated by Django 4.1.2 on 2023-04-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathsu_system', '0003_remove_member_picture_member_baptism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pro_pic',
            field=models.ImageField(default='profile.jpg', upload_to='profile_pics'),
        ),
    ]
