# Generated by Django 4.1.2 on 2023-04-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathsu_system', '0004_member_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cur_level',
            field=models.CharField(choices=[('high_school', 'high_school'), ('vocation', 'vocation'), ('tetiary', 'tetiary')], default='100', max_length=50),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('other', 'other')], default='single', max_length=50),
        ),
    ]
