# Generated by Django 4.1.2 on 2023-04-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cathsu_system', '0005_alter_member_cur_level_alter_member_marital_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('list', models.JSONField()),
            ],
        ),
    ]
